# Generated by Django 6.0.1 on 2026-04-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('branch_name', models.CharField(max_length=255)),
                ('industry_category', models.CharField(max_length=100)),
                ('vat_number', models.CharField(max_length=15, unique=True)),
                ('country_code', models.CharField(max_length=2)),
                ('national_address_code', models.CharField(max_length=20)),
                ('street_name', models.CharField(max_length=255)),
                ('building_number', models.CharField(max_length=10)),
                ('city_sub_division', models.CharField(max_length=255)),
                ('city_name', models.CharField(max_length=100)),
                ('postal_zone', models.CharField(max_length=10)),
                ('cr_number', models.CharField(max_length=20, unique=True)),
                ('invoice_category', models.CharField(choices=[('1100', 'Standard & Simplified'), ('1000', 'Standard Only'), ('0100', 'Simplified Only')], default='1100', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'branch_name'],
            },
        ),
    ]
