# Generated by Django 6.0.1 on 2026-04-19 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset_id", models.CharField(max_length=255)),
                ("egs_sw_serial_number", models.CharField(max_length=255)),
                ("otp", models.CharField(max_length=255)),
                ("csr_content", models.TextField(blank=True)),
                ("csid_response", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="organization.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["organization__name", "asset_id"],
                "unique_together": {("organization", "asset_id")},
            },
        ),
    ]
