# Generated by Django 6.0.1 on 2026-04-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0002_device"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="pcsid",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
