# Generated by Django 6.0.1 on 2026-04-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0003_device_pcsid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="pcsid",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
