# Generated by Django 6.0.4 on 2026-06-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_devicekeymaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Only active organizations can register devices.', verbose_name='Active'),
        ),
    ]
