# Generated by Django 6.0.4 on 2026-06-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_organization_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='invoice_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='device',
            name='last_invoice_hash',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
