# Generated by Django 6.0.4 on 2026-06-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_device_invoice_counter_device_last_invoice_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='invoice_counter',
        ),
        migrations.RemoveField(
            model_name='device',
            name='last_invoice_hash',
        ),
        migrations.AddField(
            model_name='organization',
            name='invoice_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organization',
            name='last_invoice_hash',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
