# Generated by Django 6.0.4 on 2026-06-06 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0007_organization_api_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('invoice', 'Invoice'), ('credit_note', 'Credit Note'), ('debit_note', 'Debit Note')], max_length=20)),
                ('payload', models.JSONField(help_text='Raw request payload preserved as-is.')),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('submitted', 'Submitted'), ('rejected', 'Rejected')], default='received', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_submissions', to='organization.device')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_submissions', to='organization.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
