# Generated by Django 6.0.4 on 2026-06-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesubmission',
            name='invoice_hash',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='invoicesubmission',
            name='invoice_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicesubmission',
            name='qr_code_data',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoicesubmission',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicesubmission',
            name='xml_document',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoicesubmission',
            name='zatca_response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
