# Generated by Django 6.0.6 on 2026-06-22 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_invoicesubmission_icv_and_status_choices'),
        ('organization', '0010_organization_email_organization_owner_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebitNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(help_text='Raw request payload preserved as-is.')),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('submitted', 'Submitted'), ('not_submitted', 'Not Submitted')], default='received', max_length=20)),
                ('icv', models.PositiveIntegerField(blank=True, null=True)),
                ('invoice_uuid', models.UUIDField(blank=True, null=True)),
                ('xml_document', models.TextField(blank=True)),
                ('invoice_hash', models.CharField(blank=True, max_length=512)),
                ('qr_code_data', models.TextField(blank=True)),
                ('zatca_response', models.JSONField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_notes', to='organization.device')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_notes', to='organization.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(help_text='Raw request payload preserved as-is.')),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('submitted', 'Submitted'), ('not_submitted', 'Not Submitted')], default='received', max_length=20)),
                ('icv', models.PositiveIntegerField(blank=True, null=True)),
                ('invoice_uuid', models.UUIDField(blank=True, null=True)),
                ('xml_document', models.TextField(blank=True)),
                ('invoice_hash', models.CharField(blank=True, max_length=512)),
                ('qr_code_data', models.TextField(blank=True)),
                ('zatca_response', models.JSONField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='organization.device')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='organization.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(help_text='Raw request payload preserved as-is.')),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('submitted', 'Submitted'), ('not_submitted', 'Not Submitted')], default='received', max_length=20)),
                ('icv', models.PositiveIntegerField(blank=True, null=True)),
                ('invoice_uuid', models.UUIDField(blank=True, null=True)),
                ('xml_document', models.TextField(blank=True)),
                ('invoice_hash', models.CharField(blank=True, max_length=512)),
                ('qr_code_data', models.TextField(blank=True)),
                ('zatca_response', models.JSONField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system_return_number', models.CharField(blank=True, max_length=255)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_notes', to='organization.device')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_notes', to='organization.organization')),
                ('original_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes', to='invoices.invoice')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='InvoiceSubmission',
        ),
    ]
