# Generated by Django 6.0.6 on 2026-06-23 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_debitnote_invoice_creditnote_and_more'),
        ('organization', '0010_organization_email_organization_owner_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debitnote',
            name='device',
        ),
        migrations.RemoveField(
            model_name='debitnote',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='device',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='organization',
        ),
        migrations.CreateModel(
            name='InvoiceSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('invoice', 'Invoice'), ('credit_note', 'Credit Note'), ('debit_note', 'Debit Note')], max_length=20)),
                ('payload', models.JSONField(help_text='Raw request payload preserved as-is.')),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('submitted', 'Submitted'), ('not_submitted', 'Not Submitted')], default='received', max_length=20)),
                ('icv', models.PositiveIntegerField(blank=True, null=True)),
                ('invoice_uuid', models.UUIDField(blank=True, null=True)),
                ('xml_document', models.TextField(blank=True)),
                ('invoice_hash', models.CharField(blank=True, max_length=512)),
                ('qr_code_data', models.TextField(blank=True)),
                ('zatca_response', models.JSONField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system_return_number', models.CharField(blank=True, max_length=255)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_submissions', to='organization.device')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_submissions', to='organization.organization')),
                ('original_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes', to='invoices.invoicesubmission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='CreditNote',
        ),
        migrations.DeleteModel(
            name='DebitNote',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
