# Generated by Django 6.0.6 on 2026-06-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_remove_debitnote_device_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesubmission',
            name='invoice_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
