# Generated by Django 6.0.6 on 2026-06-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_backfill_invoice_number'),
        ('organization', '0010_organization_email_organization_owner_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='invoicesubmission',
            constraint=models.UniqueConstraint(fields=('organization', 'document_type', 'invoice_number'), name='unique_invoice_number_per_org_and_type'),
        ),
    ]
