# Generated by Django 6.0.6 on 2026-07-14 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_invoicesubmission_unique_invoice_number_per_org_and_type'),
        ('organization', '0010_organization_email_organization_owner_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSubmissionFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('invoice', 'Invoice'), ('credit_note', 'Credit Note'), ('debit_note', 'Debit Note')], max_length=20)),
                ('invoice_number', models.CharField(blank=True, default='', max_length=100)),
                ('payload', models.JSONField()),
                ('zatca_response', models.JSONField(blank=True, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_submission_failures', to='organization.device')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_submission_failures', to='organization.organization')),
                ('resolved_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='invoices.invoicesubmission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
